[tool.poetry]
name = "dsa"
version = "0.1.0"
description = ""
authors = ["Nikhil Mhatre <nikhil.mhatre93@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pymongo = "^4.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
